# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bb2a81d0e1b1e14d399cc9b858aae496610c5b46d030d6b2fdf680adcacd89b41f49da961026f7eda6602340cdb795bb70fd58fbc2ac489005d107002839651

test:
  secret_key_base: 70f31f71741d50aeef5b43a8719b5daa2a8f8cb429e8acb5bbd4ddd860a6fb5f822f9124dd5a89af18db92dce2ecdd3bfe46124dc3302cf9d2e85308b1ee747b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
